AWSTemplateFormatVersion: '2010-09-09'
Description: Template para criacao de usuario do sftp transfer

Parameters:
  UserName:
    Type: String
  HomeDirectory:
    Type: String
  Role:
    Type: String
  ServerId:
    Type: String
  KeySsh:
    Type: String

Resources:
  UserSftp:
    Type: AWS::Transfer::User
    Properties:
      UserName: !Ref UserName
      HomeDirectory: !Ref HomeDirectory
      Role: !Ref Role
      ServerId: !Ref ServerId
      SshPublicKeys: 
        - !Ref KeySsh
